//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.19 at 07:08:14 PM CEST 
//

package gov.nist.trec;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * gov.nist.trec package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content.
 * The Java representation of XML content can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in
 * this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _DischargeDiagnosis_QNAME = new QName("", "discharge_diagnosis");
	private final static QName _UpdateTime_QNAME = new QName("", "update_time");
	private final static QName _Deid_QNAME = new QName("", "deid");
	private final static QName _Subtype_QNAME = new QName("", "subtype");
	private final static QName _AdmitDiagnosis_QNAME = new QName("", "admit_diagnosis");
	private final static QName _Year_QNAME = new QName("", "year");
	private final static QName _ChiefComplaint_QNAME = new QName("", "chief_complaint");
	private final static QName _Checksum_QNAME = new QName("", "checksum");
	private final static QName _ReportText_QNAME = new QName("", "report_text");
	private final static QName _DownlaodTime_QNAME = new QName("", "downlaod_time");
	private final static QName _Type_QNAME = new QName("", "type");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
	 * gov.nist.trec
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Report }
	 * 
	 */
	public Report createReport() {
		return new Report();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "discharge_diagnosis")
	public JAXBElement<String> createDischargeDiagnosis(String value) {
		return new JAXBElement<String>(_DischargeDiagnosis_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "update_time")
	public JAXBElement<String> createUpdateTime(String value) {
		return new JAXBElement<String>(_UpdateTime_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "deid")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	public JAXBElement<String> createDeid(String value) {
		return new JAXBElement<String>(_Deid_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "subtype")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	public JAXBElement<String> createSubtype(String value) {
		return new JAXBElement<String>(_Subtype_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "admit_diagnosis")
	public JAXBElement<BigDecimal> createAdmitDiagnosis(BigDecimal value) {
		return new JAXBElement<BigDecimal>(_AdmitDiagnosis_QNAME, BigDecimal.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "year")
	public JAXBElement<BigInteger> createYear(BigInteger value) {
		return new JAXBElement<BigInteger>(_Year_QNAME, BigInteger.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "chief_complaint")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	public JAXBElement<String> createChiefComplaint(String value) {
		return new JAXBElement<String>(_ChiefComplaint_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "checksum")
	public JAXBElement<String> createChecksum(String value) {
		return new JAXBElement<String>(_Checksum_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "report_text")
	public JAXBElement<String> createReportText(String value) {
		return new JAXBElement<String>(_ReportText_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "downlaod_time")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	public JAXBElement<String> createDownlaodTime(String value) {
		return new JAXBElement<String>(_DownlaodTime_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "type")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	public JAXBElement<String> createType(String value) {
		return new JAXBElement<String>(_Type_QNAME, String.class, null, value);
	}

}
