//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.19 at 07:08:14 PM CEST 
//

package gov.nist.trec;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}checksum"/>
 *         &lt;element ref="{}subtype"/>
 *         &lt;element ref="{}type"/>
 *         &lt;element ref="{}chief_complaint"/>
 *         &lt;element ref="{}admit_diagnosis"/>
 *         &lt;element ref="{}discharge_diagnosis"/>
 *         &lt;element ref="{}year"/>
 *         &lt;element ref="{}downlaod_time"/>
 *         &lt;element ref="{}update_time"/>
 *         &lt;element ref="{}deid"/>
 *         &lt;element ref="{}report_text"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "checksum", "subtype", "type", "chiefComplaint", "admitDiagnosis",
		"dischargeDiagnosis", "year", "downlaodTime", "updateTime", "deid", "reportText" })
@XmlRootElement(name = "report")
public class Report {

	@XmlElement(required = true)
	protected String checksum;
	@XmlElement(required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlSchemaType(name = "NCName")
	protected String subtype;
	@XmlElement(required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlSchemaType(name = "NCName")
	protected String type;
	@XmlElement(name = "chief_complaint", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlSchemaType(name = "NCName")
	protected String chiefComplaint;
	@XmlElement(name = "admit_diagnosis", required = true)
	protected BigDecimal admitDiagnosis;
	@XmlElement(name = "discharge_diagnosis", required = true)
	protected String dischargeDiagnosis;
	@XmlElement(required = true)
	protected BigInteger year;
	@XmlElement(name = "downlaod_time", required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlSchemaType(name = "NMTOKEN")
	protected String downlaodTime;
	@XmlElement(name = "update_time", required = true)
	protected String updateTime;
	@XmlElement(required = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlSchemaType(name = "NCName")
	protected String deid;
	@XmlElement(name = "report_text", required = true)
	protected String reportText;

	/**
	 * Gets the value of the checksum property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getChecksum() {
		return checksum;
	}

	/**
	 * Sets the value of the checksum property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setChecksum(String value) {
		this.checksum = value;
	}

	/**
	 * Gets the value of the subtype property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSubtype() {
		return subtype;
	}

	/**
	 * Sets the value of the subtype property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSubtype(String value) {
		this.subtype = value;
	}

	/**
	 * Gets the value of the type property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getType() {
		return type;
	}

	/**
	 * Sets the value of the type property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setType(String value) {
		this.type = value;
	}

	/**
	 * Gets the value of the chiefComplaint property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getChiefComplaint() {
		return chiefComplaint;
	}

	/**
	 * Sets the value of the chiefComplaint property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setChiefComplaint(String value) {
		this.chiefComplaint = value;
	}

	/**
	 * Gets the value of the admitDiagnosis property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 * 
	 */
	public BigDecimal getAdmitDiagnosis() {
		return admitDiagnosis;
	}

	/**
	 * Sets the value of the admitDiagnosis property.
	 * 
	 * @param value
	 *            allowed object is {@link BigDecimal }
	 * 
	 */
	public void setAdmitDiagnosis(BigDecimal value) {
		this.admitDiagnosis = value;
	}

	/**
	 * Gets the value of the dischargeDiagnosis property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDischargeDiagnosis() {
		return dischargeDiagnosis;
	}

	/**
	 * Sets the value of the dischargeDiagnosis property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDischargeDiagnosis(String value) {
		this.dischargeDiagnosis = value;
	}

	/**
	 * Gets the value of the year property.
	 * 
	 * @return possible object is {@link BigInteger }
	 * 
	 */
	public BigInteger getYear() {
		return year;
	}

	/**
	 * Sets the value of the year property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 * 
	 */
	public void setYear(BigInteger value) {
		this.year = value;
	}

	/**
	 * Gets the value of the downlaodTime property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDownlaodTime() {
		return downlaodTime;
	}

	/**
	 * Sets the value of the downlaodTime property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDownlaodTime(String value) {
		this.downlaodTime = value;
	}

	/**
	 * Gets the value of the updateTime property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getUpdateTime() {
		return updateTime;
	}

	/**
	 * Sets the value of the updateTime property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setUpdateTime(String value) {
		this.updateTime = value;
	}

	/**
	 * Gets the value of the deid property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDeid() {
		return deid;
	}

	/**
	 * Sets the value of the deid property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDeid(String value) {
		this.deid = value;
	}

	/**
	 * Gets the value of the reportText property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getReportText() {
		return reportText;
	}

	/**
	 * Sets the value of the reportText property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setReportText(String value) {
		this.reportText = value;
	}

	@Override
	public String toString() {
		return "Report [checksum=" + checksum + ", subtype=" + subtype + ", type=" + type + ", chiefComplaint="
				+ chiefComplaint + ", admitDiagnosis=" + admitDiagnosis + ", dischargeDiagnosis=" + dischargeDiagnosis
				+ ", year=" + year + ", downlaodTime=" + downlaodTime + ", updateTime=" + updateTime + ", deid=" + deid
				+ ", reportText=" + reportText + "]";
	}

}
